apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42-v1
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: http://gitlab-webservice-default.gitlab.svc:8181/root/${REPO}.git
      targetRevision: HEAD
      path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
          limit: 3
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 1m
