global:
  hosts:
    domain: localhost
    https: false
  ingress:
    configureCertmanager: false
    class: nginx
gitlab-runner:
  install: false
nginx-ingress:
  enabled: true
certmanager:
  enabled: false


